### ISSUE TITLE
Not able to receive Artnet packets

### ISSUE THREAD

**Issue by woutwoot** [robertoostenveld/esp8266_artnet_dmx512#12]
I've built this device and connected it to a simple par light to test it. (I2S mode)

It looks like everything is working, but it seems somehow I'm not able to have the ESP receive data over ArtNet.
I'm using QLC+ to send data, and it reports 1000s of packets sent, but on the web interface of the ESP I only see a very low number of packets received (around 30, does go up very very slowly over time)
I can tell the light itself is receiving DMX data because it has a blinking led for this.

I would really love to get this to work but at this point I'm not sure if I'm doing something wrong or what it may be. Any clue as to what this issue could be or how I could debug it?

**Comment by robertoostenveld** [comment]
I suggest you use the serial monitor in the Arduino IDE to connect to the ESP. On this line https://github.com/robertoostenveld/esp8266_artnet_dmx512/blob/57212159923df2f84f8e9a81104d06b9ad493831/esp8266_artnet_dmx512.ino#L183 it will print that it receives data and a bit further it will print a counter for the number of Artnet packets received. That should help you to further debug.

**Comment by robertoostenveld** [comment]
Oh, and the DMX stream that your fixture receives is sent by the ESP independently of the Artnet that it receives. In the main loop on line https://github.com/robertoostenveld/esp8266_artnet_dmx512/blob/57212159923df2f84f8e9a81104d06b9ad493831/esp8266_artnet_dmx512.ino#L578 and a bit further it sends the data of the whole universe over the serial interface, at a fixed rate. The ‎onDmxPacket‎() function only runs when an UDP packet is received and it updates the universe data.

**Comment by woutwoot** [comment]
@robertoostenveld Thank you for pointing me in the right direction. Of course it was something stupid, I was using Artnet universe 0 in QLC+ and universe 1 is what my light setup was responding to. As soon as the two matched things worked.
Thank you for this project!

**Comment by woutwoot** [comment]
Hmm, is it possible that somehow addresses are also shifted by one? My fixture starts at 1 but it seems my first channel is shifted one up in practice. Guess that's something on my end as well but just making sure :)

EDIT: Can confirm that was also stupidity on my end 😅

**Comment by robertoostenveld** [comment]
With the numbered universes and channels it can be challenging to deal with the numbering sometimes starting at 0, and sometimes at 1. Glad you figured it out and have fun with it!
