### ISSUE TITLE
gibberish on serial monitor

### ISSUE THREAD

**Issue by wannabeadjeo** [robertoostenveld/esp8266_artnet_dmx512#15]
I have had this problem since I uploaded the sketch; the serial monitor keeps sending me gibberish messages. Also, on the web server, when I try to configure it while connecting to the router, when I open the web address, it says file not found. Any solutions?
![image](https://github.com/robertoostenveld/esp8266_artnet_dmx512/assets/162305925/00dedd20-1540-4667-b1df-585cdb8f826c)

**Comment by robertoostenveld** [comment]
The gibberish suggests that you did not specify the correct baud rate for your serial port.

"File not found" suggests that you did not upload the SPIFFS data.
