### ISSUE TITLE
no dmx data received by led par

### ISSUE THREAD

**Issue by wannabeadjeo** [robertoostenveld/esp8266_artnet_dmx512#16]
I am using the i2s to send the dmx data to my par, and I wired the di pin to the Rx pin on my nodemcu esp8266, the gnd and re pin on the nodemcu gnd pin, and the vcc to the vv pin on my node mcu. I configured it on the web server, the artnet universe is univ1, the same on my qlc+, the channels are 512, the delay is 25, yet my par is not responding, but if I use my usb to dmx interface, it is working properly.
![image](https://github.com/robertoostenveld/esp8266_artnet_dmx512/assets/162305925/07bb33ee-712a-4241-80dc-e75249728b16)

**Comment by robertoostenveld** [comment]
Did you try it with the UART mode? Do you have the possibility to connect the output to an oscilloscope to see whether you see a signal?

**Comment by wannabeadjeo** [comment]
> Did you try it with the UART mode? Do you have the possibility to connect the output to an oscilloscope to see whether you see a signal?

The problem is that I don't have an oscilloscope to use. I have a question: if I will use the UART mode, do I need to put the di pin on the D4 instead of the tx pin on my Nodemcu?

**Comment by wannabeadjeo** [comment]
Sir, you can close this issue. I have found the solution; I just swapped my RS485 module.

**Comment by robertoostenveld** [comment]
That is nice to hear, have fun with the DMX converter!

**Comment by wannabeadjeo** [comment]
> That is nice to hear, have fun with the DMX converter!

Thank you so much for answering me
