### ISSUE TITLE
Wired lan

### ISSUE THREAD

**Issue by lhvandersteen** [robertoostenveld/esp8266_artnet_dmx512#8]
Hello. 

Is there a option to use a wired connection instead of wireless.  

Thank you

**Comment by robertoostenveld** [comment]
In principle yes, but then you should implement it with an arduino or other microcontroller board with a wired ethernet interface. Then you would get something similar as https://www.enttec.com/product/din/ethernet-to-dmx-rdm-adapter/

The esp8266 is a wifi microcontroller module and not suited for wired network, so my design is not of use.

**Comment by lhvandersteen** [comment]
Hello 

Thank you for the quick answer.    
Would this also be working 
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware

Or this 
 WT32-ETH01
https://a.aliexpress.com/_mM3X1ju


Thank you

**Comment by robertoostenveld** [comment]
Yes, that might work. Or an Arduino Uno with an [Ethernet Shield](https://docs.arduino.cc/retired/getting-started-guides/ArduinoEthernetShield), or an Adafruit Feather with the [FeatherWing](https://www.adafruit.com/product/3201). But none of them will work with the firmware that is in this repository; they all would require a significant rewrite. I think that - at best - 25% of the code in my repository would be reusable, the rest would probably have to be written from scratch.
