### ISSUE TITLE
why use uart

### ISSUE THREAD

**Issue by lesleylemmens** [robertoostenveld/esp8266_artnet_dmx512#9]
Hi, if i2s works better, why do i need to also make the uart connection and the toggle switch?
in wich file do i enable i2s?

**Comment by robertoostenveld** [comment]
There have been reports by some that i2s works good for them, by others (including myself) that uart works good for them. It is a choice that you can make. If you add the toggle switch, you can easily compare. Without the toggle switch you'll have to use a soldering iron to switch between the two options.

In line 37 and 46 of [esp8266_artnet_dmx512.ino](https://github.com/robertoostenveld/esp8266_artnet_dmx512/blob/main/esp8266_artnet_dmx512.ino) you can enable/disable the two options. By default both are enabled; this comes at the expense of slightly higher computational load for the microprocessor, so if you know that you will only be using one you can disable the other.
